const text = document.getElementById("text");
const audio = document.getElementsByClassName("audio")
const key = document.getElementsByClassName("key")
const Accurate = document.querySelector(".Accurate")
const beep = document.getElementsByClassName("beep")[0]
const container = document.getElementsByClassName("container")[0]
const mm = document.getElementsByClassName("mm")[0]
const WPM = document.getElementsByClassName("WPM")[0]
let     startSupport = 1;
let minutes = 0;
let SpeedSupport = 0;
let seconds = 0;
const ss = document.getElementsByClassName("ss")[0]
let Right = 0;
const audioElement = document.getElementsByClassName("audio")[0];
audio[0].addEventListener('loadedmetadata', () => {
  const durationInSeconds = audio[0].duration;
  const durationInMilliseconds = durationInSeconds ;
});
let Left = 0;
const A_wordsArray = [
  "Absurd",
  "Anchor",
  "Agile",
  "Anthem",
  "Arrow",
  "Ambush",
  "Alert",
  "Arctic",
  "Aroma",
  "Almond",
  "Artist",
  "Ample",
  "Assemble",
  "Autumn",
  "Adept",
  "Avenue",
  "Antenna",
  "Amuse",
  "Arcade",
  "Ache",
  "Alloy",
  "Airtight",
  "Armadillo",
  "Avid",
  "Absorb",
  "Acorn",
  "Acoustic",
  "Apricot",
  "Aplenty",
  "Aquatic",
  "Allure",
  "Ashen",
  "Assure",
  "Ankle",
  "Admire",
  "Asteroid",
  "Apology",
  "Acrobat",
  "Anguish",
  "Ancient",
  "Astral",
  "Apparel",
  "Arise",
  "Anatomy",
  "Assemble",
  "Aroma",
  "Apex",
  "Accurate",
  "Abrupt",
  "Apple",
  "Amigo",
  "Accordion",
  "Airy",
  "Alley",
  "Agitate",
  "Ascent",
  "Anchor",
  "Aura",
  "Arcade",
  "Attractive",
  "Avert",
  "Aspirin",
  "Angler",
  "Afar",
  "Asylum",
  "Assemble",
  "Atom",
  "Album",
  "Aster",
  "Agility",
  "Archery",
  "Angst",
  "Astound",
  "Amaze",
  "Accolade",
  "Ashore",
  "Amenity",
  "Appoint",
  "Arcade",
  "Acrylic",
  "Armory",
  "Archaic",
  "Alibi",
  "Ashen",
  "Apparel",
  "Autograph",
  "Acorn",
  "Assorted",
  "Audition",
  "Anthem",
  "Ample",
  "Aversion",
  "Auburn",
  "Algebra",
  "Arrive",
  "Amused",
  "Aquatic",
  "Astute",
  "Afire",
  "Above",
  "Abound",
  "Autumn",
  "Agile",
  "Apron",
  "Abyss",
  "Ascend",
  "Acclaim",
  "Apparel",
  "Adept",
  "Affluent",
  "Ashen",
  "Airtight",
  "Aroma",
  "Amuse",
  "Ambient",
  "Acidic",
  "Archway",
  "Anvil",
  "Assemble",
  "Agitate",
  "Addict",
  "Array",
  "Alight",
  "Amidst",
  "Astonish",
  "Anguish",
  "Azalea",
  "Amigo",
  "Absorb",
  "Armored",
  "Ample",
  "Astronomy",
  "Asylum",
  "Adrift",
  "Artist",
  "Accustom",
  "Azure",
  "Alphabet",
  "Aspire",
  "Ardent",
  "Abyss",
  "Animate",
  "Appease",
  "Anchor",
  "Arcade",
  "Ache",
  "Alloy",
  "Airtight",
  "Armadillo",
  "Avid",
  "Absorb",
  "Acorn",
  "Acoustic",
  "Apricot",
  "Aplenty",
  "Aquatic",
  "Allure",
  "Ashen",
  "Assure",
  "Ankle",
  "Admire",
  "Asteroid",
  "Apology",
  "Acrobat",
  "Anguish",
  "Ancient",
  "Astral",
  "Apparel",
  "Arise",
  "Anatomy",
  "Assemble",
  "Aroma",
  "Apex",
  "Accurate",
  "Abrupt",
  "Apple",
  "Amigo",
  "Accordion",
  "Airy",
  "Alley",
  "Agitate",
  "Ascent",
  "Anchor",
  "Aura",
  "Arcade",
  "Attractive",
  "Avert",
  "Aspirin",
  "Angler",
  "Afar",
  "Asylum",
  "Assemble",
  "Atom",
  "Album",
  "Aster",
  "Agility",
  "Archery",
  "Angst",
  "Astound",
  "Amaze",
  "Accolade",
  "Ashore",
  "Amenity",
  "Appoint",
  "Arcade",
  "Acrylic",
  "Armory",
  "Archaic",
  "Alibi",
  "Ashen",
  "Apparel",
  "Autograph",
  "Acorn",
  "Assorted",
  "Audition",
  "Anthem",
  "Ample",
  "Aversion",
  "Auburn",
  "Algebra",
  "Arrive",
  "Amused",
  "Aquatic",
  "Astute",
  "Afire",
  "Above",
  "Abound",
  "Autumn",
  "Agile",
  "Apron",
  "Abyss",
  "Ascend",
  "Acclaim",
  "Apparel",
  "Adept",
  "Affluent",
  "Ashen",
  "Airtight",
  "Aroma",
  "Amuse",
  "Ambient",
  "Acidic",
  "Archway",
  "Anvil",
  "Assemble",
  "Agitate",
  "Addict",
  "Array",
  "Alight",
  "Amidst",
  "Astonish",
  "Anguish",
  "Azalea",
  "Amigo",
  "Absorb",
  "Armored",
  "Ample",
  "Astronomy",
  "Asylum",
  "Adrift",
  "Artist",
  "Accustom",
  "Azure",
  "Alphabet",
  "Aspire",
  "Ardent",
  "Abyss",
  "Animate",
  "Appease",
  "Anchor",
  "Arcade",
  "Ache",
  "Alloy",
  "Airtight",
  "Armadillo",
  "Avid",
  "Absorb",
  "Acorn",
  "Acoustic",
  "Apricot",
  "Aplenty",
  "Aquatic",
  "Allure",
  "Ashen",
  "Assure",
  "Ankle",
  "Admire",
  "Asteroid",
  "Apology",
  "Acrobat",
  "Anguish",
  "Ancient",
  "Astral",
  "Apparel",
  "Arise",
  "Anatomy",
  "Assemble",
  "Aroma",
  "Apex",
  "Accurate",
  "Abrupt",
  "Apple",
  "Amigo",
  "Accordion",
  "Airy",
  "Alley",
  "Agitate",
  "Ascent",
  "Anchor",
  "Aura",
  "Arcade",
  "Attractive",
  "Avert",
  "Aspirin",
  "Angler",
  "Afar",
  "Asylum",
  "Assemble",
  "Atom",
  "Album",
  "Aster",
  "Agility",
  "Archery",
  "Angst",
  "Astound",
  "Amaze",
  "Accolade",
  "Ashore",
  "Amenity",
  "Appoint",
  "Arcade",
  "Acrylic",
  "Armory",
  "Archaic",
  "Alibi",
  "Ashen",
  "Apparel",
  "Autograph",
  "Acorn",
  "Assorted",
  "Audition",
  "Anthem",
  "Ample",
  "Aversion",
  "Auburn",
  "Algebra",
  "Arrive",
  "Amused",
  "Aquatic",
  "Astute",
  "Afire",
  "Above",
  "Abound",
  "Autumn",
  "Agile",
  "Apron",
  "Abyss",
  "Ascend",
  "Acclaim",
  "Apparel",
  "Adept",
  "Affluent",
  "Ashen",
  "Airtight",
  "Aroma",
  "Amuse",
  "Ambient",
  "Acidic",
  "Archway",
  "Anvil",
  "Assemble",
  "Agitate",
  "Addict",
  "Array",
  "Alight",
  "Amidst",
  "Astonish",
  "Anguish",
  "Azalea",
  "Amigo",
  "Absorb",
  "Armored",
  "Ample",
  "Astronomy",
  "Asylum",
  "Adrift",
  "Artist",
  "Accustom",
  "Azure",
  "Alphabet",
  "Aspire",
  "Ardent",
  "Abyss",
  "Animate",
  "Appease",
  "Anchor",
  "Arcade",
  "Ache",
  "Alloy",
  "Airtight",
  "Armadillo",
  "Avid",
  "Absorb",
  "Acorn",
  "Acoustic",
  "Apricot",
  "Aplenty",
  "Aquatic",
  "Allure",
  "Ashen",
  "Assure",
  "Ankle",
  "Admire",
  "Asteroid",
  "Apology",
  "Acrobat",
  "Anguish",
  "Ancient",
  "Astral",
  "Apparel",
  "Arise",
  "Anatomy",
  "Assemble",
  "Aroma",
  "Apex",
  "Accurate",
  "Abrupt",
  "Apple",
  "Amigo",
  "Accordion",
  "Airy",
  "Alley",
  "Agitate",
  "Ascent",
  "Anchor",
  "Aura",
  "Arcade",
  "Attractive",
  "Avert",
  "Aspirin",
  "Angler",
  "Afar",
  "Asylum",
  "Assemble",
  "Atom",
  "Album",
  "Aster",
  "Agility",
  "Archery",
  "Angst",
  "Astound",
  "Amaze",
  "Accolade",
  "Ashore",
  "Amenity",
  "Appoint",
  "Arcade",
  "Acrylic",
  "Armory",
  "Archaic",
  "Alibi",
  "Ashen",
  "Apparel",
  "Autograph",
  "Acorn",
  "Assorted",
  "Audition",
  "Anthem",
  "Ample",
  "Aversion",
  "Auburn",
  "Algebra",
  "Arrive",
  "Amused",
  "Aquatic",
  "Astute",
  "Afire",
  "Above",
  "Abound",
  "Autumn",
  "Agile",
  "Apron",
  "Abyss",
  "Ascend",
  "Acclaim",
  "Apparel",
  "Adept",
  "Affluent",
  "Ashen",
  "Airtight",
  "Aroma",
  "Amuse",
  "Ambient",
  "Acidic",
  "Archway",
  "Anvil",
  "Assemble",
  "Agitate",
  "Addict",
  "Array",
  "Alight",
  "Amidst",
  "Astonish",
  "Anguish",
  "Azalea",
  "Amigo",
  "Absorb",
  "Armored",
  "Ample",
  "Astronomy",
  "Asylum",
  "Adrift",
  "Artist",
  "Accustom",
  "Azure",
  "Alphabet",
  "Aspire",
  "Ardent",
  "Abyss",
  "Animate",
  "Appease",
  "Anchor",
  "Arcade",
  "Ache",
  "Alloy",
  "Airtight",
  "Armadillo",
  "Avid",
  "Absorb",
  "Acorn",
  "Acoustic",
  "Apricot",
  "Aplenty",
  "Aquatic",
  "Allure",
  "Ashen",
  "Assure",
  "Ankle",
  "Admire",
  "Asteroid",
  "Apology",
  "Acrobat",
  "Anguish",
  "Ancient",
  "Astral",
  "Apparel",
  "Arise",
  "Anatomy",
  "Assemble",
  "Aroma",
  "Apex",
  "Accurate",
  "Abrupt",
  "Apple",
  "Amigo",
  "Accordion",
  "Airy",
  "Alley",
  "Agitate",
  "Ascent",
  "Anchor",
  "Aura",
  "Arcade",
  "Attractive",
  "Avert",
  "Aspirin",
  "Angler",
  "Afar",
  "Asylum",
  "Assemble",
  "Atom",
  "Album",
  "Aster",
  "Agility",
  "Archery",
  "Angst",
  "Astound",
  "Amaze",
  "Accolade",
  "Ashore",
  "Amenity",
  "Appoint",
  "Arcade",
  "Acrylic",
  "Armory",
  "Archaic",
  "Alibi",
  "Ashen",
  "Apparel",
  "Autograph",
  "Acorn",
  "Assorted",
  "Audition",
  "Anthem",
  "Ample",
  "Aversion",
  "Auburn",
  "Algebra",
  "Arrive",
  "Amused",
  "Aquatic",
  "Astute",
  "Afire",
  "Above",
  "Abound",
  "Autumn",
  "Agile",
  "Apron",
  "Abyss",
  "Ascend",
  "Acclaim",
  "Apparel",
  "Adept",
  "Affluent",
  "Ashen",
  "Airtight",
  "Aroma",
  "Amuse",
  "Ambient",
  "Acidic",
  "Archway",
  "Anvil",
  "Assemble",
  "Agitate",
  "Addict",
  "Array",
  "Alight",
  "Amidst",
  "Astonish",
  "Anguish",
  "Azalea",
  "Amigo",
  "Absorb",
  "Armored",
  "Ample",
  "Astronomy",
  "Asylum",
  "Adrift",
  "Artist",
  "Accustom",
  "Azure",
  "Alphabet",
  "Aspire",
  "Ardent",
  "Abyss",
  "Animate",
  "Appease",
  "Anchor",
  "Arcade",
  "Ache",
  "Alloy",
  "Airtight",
  "Armadillo",
  "Avid",
  "Absorb",
  "Acorn",
  "Acoustic",
  "Apricot",
  "Aplenty",
  "Aquatic",
  "Allure",
  "Ashen",
  "Assure",
  "Ankle",
  "Admire",
  "Asteroid",
  "Apology",
  "Acrobat",
  "Anguish",
  "Ancient",
  "Astral",
  "Apparel",
  "Arise",
  "Anatomy",
  "Assemble",
  "Aroma",
  "Apex",
  "Accurate",
  "Abrupt",
  "Apple",
  "Amigo",
  "Accordion",
  "Airy",
  "Alley",
  "Agitate",
  "Ascent",
  "Anchor",
  "Aura",
  "Arcade",
  "Attractive",
  "Avert",
  "Aspirin",
  "Angler",
  "Afar",
  "Asylum",
  "Assemble",
  "Atom",
  "Album",
  "Aster",
  "Agility",
  "Archery",
  "Angst",
  "Astound",
  "Amaze",
  "Accolade",
  "Ashore",
  "Amenity",
  "Appoint",
  "Arcade",
  "Acrylic",
  "Armory",
  "Archaic",
  "Alibi",
  "Ashen",
  "Apparel",
  "Autograph",
  "Acorn",
  "Assorted",
  "Audition",
  "Anthem",
  "Ample",
  "Aversion",
  "Auburn",
  "Algebra",
  "Arrive",
  "Amused",
  "Aquatic",
  "Astute",
  "Afire",
  "Above",
  "Abound",
  "Autumn",
  "Agile",
  "Apron",
  "Abyss",
  "Ascend",
  "Acclaim",
  "Apparel",
  "Adept",
  "Affluent",
  "Ashen",
  "Airtight",
  "Aroma",
  "Amuse",
  "Ambient",
  "Acidic",
  "Archway",
  "Anvil",
  "Assemble",
  "Agitate",
  "Addict",
  "Array",
  "Alight",
  "Amidst",
  "Astonish",
  "Anguish",
  "Azalea",
  "Amigo",
  "Absorb",
  "Armored",
  "Ample",
  "Astronomy",
  "Asylum",
  "Adrift",
  "Artist",
  "Accustom",
  "Azure",
  "Alphabet",
  "Aspire",
  "Ardent",
  "Abyss",
  "Animate",
  "Appease",
  "Anchor",
  "Arcade",
  "Ache",
  "Alloy",
  "Airtight",
  "Armadillo",
  "Avid",
  "Absorb",
  "Acorn",
  "Acoustic",
  "Apricot",
  "Aplenty",
  "Aquatic",
  "Allure",
  "Ashen",
  "Assure",
  "Ankle",
  "Admire",
  "Asteroid",
  "Apology",
  "Acrobat",
  "Anguish",
  "Ancient",
  "Astral",
  "Apparel",
  "Arise",
  "Anatomy",
  "Assemble",
  "Aroma",
  "Apex",
  "Accurate",
  "Abrupt",
  "Apple",
  "Amigo",
  "Accordion",
  "Airy",
  "Alley",
  "Agitate",
  "Ascent",
  "Anchor",
  "Aura",
  "Arcade",
  "Attractive",
  "Avert",
  "Aspirin",
  "Angler",
  "Afar",
  "Asylum",
  "Assemble",
  "Atom",
  "Album",
  "Aster",
  "Agility",
  "Archery",
  "Angst",
  "Astound",
  "Amaze",
  "Accolade",
  "Ashore",
  "Amenity",
  "Appoint",
  "Arcade",
  "Acrylic",
  "Armory",
  "Archaic",
  "Alibi",
  "Ashen",
  "Apparel",
  "Autograph",
  "Acorn",
  "Assorted",
  "Audition",
  "Anthem",
  "Ample",
  "Aversion",
  "Auburn",
  "Algebra",
  "Arrive",
  "Amused",
  "Aquatic",
  "Astute",
  "Afire",
  "Above",
  "Abound",
  "Autumn",
  "Agile",
  "Apron",
  "Abyss",
  "Ascend",
  "Acclaim",
  "Apparel",
  "Adept",
  "Affluent",
  "Ashen",
  "Airtight",
  "Aroma",
  "Amuse",
  "Ambient",
  "Acidic",
  "Archway",
  "Anvil",
  "Assemble",
  "Agitate",
  "Addict",
  "Array",
  "Alight",
  "Amidst",
  "Astonish",
  "Anguish",
  "Azalea",
  "Amigo",
  "Absorb",
  "Armored",
  "Ample",
  "Astronomy",
  "Asylum",
  "Adrift",
  "Artist",
  "Accustom",
  "Azure",
  "Alphabet",
  "Aspire",
  "Ardent",
  "Abyss",
  "Animate",
  "Appease",
  "Anchor",
  "Arcade",
  "Ache",
  "Alloy",
  "Airtight",
  "Armadillo",
  "Avid",
  "Absorb",
  "Acorn",
  "Acoustic",
  "Apricot",
  "Aplenty",
  "Aquatic",
  "Allure",
  "Ashen",
  "Assure",
  "Ankle",
  "Admire",
  "Asteroid",
  "Apology",
  "Acrobat",
  "Anguish",
  "Ancient",
  "Astral",
  "Apparel",
  "Arise",
  "Anatomy",
  "Assemble",
  "Aroma",
  "Apex",
  "Accurate",
  "Abrupt",
  "Apple",
  "Amigo",
  "Accordion",
  "Airy",
  "Alley",
  "Agitate",
  "Ascent",
  "Anchor",
  "Aura",
  "Arcade",
  "Attractive",
  "Avert",
  "Aspirin",
  "Angler",
  "Afar",
  "Asylum",
  "Assemble",
  "Atom",
  "Album",
  "Aster",
  "Agility",
  "Archery",
  "Angst",
  "Astound",
  "Amaze",
  "Accolade",
  "Ashore",
  "Amenity",
  "Appoint",
  "Arcade",
  "Acrylic",
  "Armory",
  "Archaic",
  "Alibi",
  "Ashen",
  "Apparel",
  "Autograph",
  "Acorn",
  "Assorted",
  "Audition",
  "Anthem",
  "Ample",
  "Aversion",
  "Auburn",
  "Algebra",
  "Arrive",
  "Amused",
  "Aquatic",
  "Astute",
  "Afire",
  "Above",
  "Abound",
  "Autumn",
  "Agile",
  "Apron",
  "Abyss",
  "Ascend",
  "Acclaim",
  "Apparel",
  "Adept",
  "Affluent",
  "Ashen",
  "Airtight",
  "Aroma",
  "Amuse",
  "Ambient",
  "Acidic",
  "Archway",
  "Anvil",
  "Assemble",
  "Agitate",
  "Addict",
  "Array",
  "Alight",
  "Amidst",
  "Astonish",
  "Anguish",
  "Azalea",
  "Amigo",
  "Absorb",
  "Armored",
  "Ample",
  "Astronomy",
  "Asylum",
  "Adrift",
  "Artist",
  "Accustom",
  "Azure",
  "Alphabet",
  "Aspire",
  "Ardent",
  "Abyss",
  "Animate",
  "Appease",
  "Anchor",
  "Arcade",
  "Ache",
  "Alloy",
  "Airtight",
  "Armadillo",
  "Avid",
  "Absorb",
  "Acorn",
  "Acoustic",
  "Apricot",
  "Aplenty",
  "Aquatic",
  "Allure",
  "Ashen",
  "Assure",
  "Ankle",
  "Admire",
  "Asteroid",
  "Apology",
  "Acrobat",
  "Anguish",
  "Ancient",
  "Astral",
  "Apparel",
  "Arise",
  "Anatomy",
  "Assemble",
  "Aroma",
  "Apex",
  "Accurate",
  "Abrupt",
  "Apple",
  "Amigo",
  "Accordion",
  "Airy",
  "Alley",
  "Agitate",
  "Ascent",
  "Anchor",
  "Aura",
  "Arcade",
  "Attractive",
  "Avert",
  "Aspirin",
  "Angler",
  "Afar",
  "Asylum",
  "Assemble",
  "Atom",
  "Album",
  "Aster",
  "Agility",
  "Archery",
  "Angst",
  "Astound",
  "Amaze",
  "Accolade",
  "Ashore",
  "Amenity",
  "Appoint",
  "Arcade",
  "Acrylic",
  "Armory",
  "Archaic",
  "Alibi",
  "Ashen",
  "Apparel",
  "Autograph",
  "Acorn",
  "Assorted",
  "Audition",
  "Anthem",
  "Ample",
  "Aversion",
  "Auburn",
  "Algebra",
  "Arrive",
  "Amused",
  "Aquatic",
  "Astute",
  "Afire",
  "Above",
  "Abound",
  "Autumn",
  "Agile",
  "Apron",
  "Abyss",
  "Ascend",
  "Acclaim",
  "Apparel",
  "Adept",
  "Affluent",
  "Ashen",
  "Airtight",
  "Aroma",
  "Amuse",
  "Ambient",
  "Acidic",
  "Archway",
  "Anvil",
  "Assemble",
  "Agitate",
  "Addict",
  "Array",
  "Alight",
  "Amidst",
  "Astonish",
  "Anguish",
  "Azalea",
  "Amigo",
  "Absorb",
  "Armored",
  "Ample",
  "Astronomy",
  "Asylum",
  "Adrift",
  "Artist",
  "Accustom",
  "Azure",
  "Alphabet",
  "Aspire",
  "Ardent",
  "Abyss",
  "Animate",
  "Appease",
  "Anchor",
  "Arcade",
  "Ache",
  "Alloy",
  "Airtight",
  "Armadillo",
  "Avid",
  "Absorb",
  "Acorn",
  "Acoustic",
  "Apricot",
  "Aplenty",
  "Aquatic",
  "Allure",
  "Ashen",
  "Assure",
  "Ankle",
  "Admire",
  "Asteroid",
  "Apology",
  "Acrobat",
  "Anguish",
  "Ancient",
  "Astral",
  "Apparel",
  "Arise",
  "Anatomy",
  "Assemble",
  "Aroma",
  "Apex",
  "Accurate",
  "Abrupt",
  "Apple",
  "Amigo",
  "Accordion",
  "Airy",
  "Alley",
  "Agitate",
  "Ascent",
  "Anchor",
  "Aura",
  "Arcade",
  "Attractive",
  "Avert",
  "Aspirin",
  "Angler",
  "Afar",
  "Asylum",
  "Assemble",
  "Atom",
  "Album",
  "Aster",
  "Agility",
  "Archery",
  "Angst",
  "Astound",
  "Amaze",
  "Accolade",
  "Ashore",
  "Amenity",
  "Appoint",
  "Arcade",
  "Acrylic",
  "Armory",
  "Archaic",
  "Alibi",
  "Ashen",
  "Apparel",
  "Autograph",
  "Acorn",
  "Assorted",
  "Audition",
  "Anthem",
  "Ample",
  "Aversion",
  "Auburn",
  "Algebra",
  "Arrive",
  "Amused",
  "Aquatic",
  "Astute",
  "Afire",
  "Above",
  "Abound",
  "Autumn",
  "Agile",
  "Apron",
  "Abyss",
  "Ascend",
  "Acclaim",
  "Apparel",
  "Adept",
  "Affluent",
  "Ashen",
  "Airtight",
  "Aroma",
  "Amuse",
  "Ambient",
  "Acidic",
  "Archway",
  "Anvil",
  "Assemble",
  "Agitate",
  "Addict",
  "Array",
  "Alight",
  "Amidst",
  "Astonish",
  "Anguish",
  "Azalea",
  "Amigo",
  "Absorb",
  "Armored",
  "Ample",
  "Astronomy",
  "Asylum",
  "Adrift",
  "Artist",
  "Accustom",
  "Azure",
  "Alphabet",
  "Aspire",
  "Ardent",
  "Abyss",
  "Animate",
  "Appease",
  "Anchor",
  "Arcade",
  "Ache",
  "Alloy",
  "Airtight",
  "Armadillo",
  "Avid",
  "Absorb",
  "Acorn",
  "Acoustic",
  "Apricot",
  "Aplenty",
  "Aquatic",
  "Allure",
  "Ashen",
  "Assure",
  "Ankle",
  "Admire",
  "Asteroid",
  "Apology",
  "Acrobat",
  "Anguish",
  "Ancient",
  "Astral",
  "Apparel",
  "Arise",
  "Anatomy",
  "Assemble",
  "Aroma",
  "Apex",
  "Accurate",
  "Abrupt",
  "Apple",
  "Amigo",
  "Accordion",
  "Airy",
  "Alley",
  "Agitate",
  "Ascent",
  "Anchor",
  "Aura",
  "Arcade",
  "Attractive",
  "Avert",
  "Aspirin",
  "Angler",
  "Afar",
  "Asylum",
  "Assemble",
  "Atom",
  "Album",
  "Aster",
  "Agility",
  "Archery",
  "Angst",
  "Astound",
  "Amaze",
  "Accolade",
  "Ashore",
  "Amenity",
  "Appoint",
  "Arcade",
  "Acrylic",
  "Armory",
  "Archaic",
  "Alibi",
  "Ashen",
  "Apparel",
  "Autograph",
  "Acorn",
  "Assorted",
  "Audition",
  "Anthem",
  "Ample",
  "Aversion",
  "Auburn",
  "Algebra",
  "Arrive",
  "Amused",
  "Aquatic",
  "Astute",
  "Afire",
  "Above",
  "Abound",
  "Autumn",
  "Agile",
  "Apron",
  "Abyss",
  "Ascend",
  "Acclaim",
  "Apparel",
  "Adept",
  "Affluent",
  "Ashen",
  "Airtight",
  "Aroma",
  "Amuse",
  "Ambient",
  "Acidic",
  "Archway",
  "Anvil",
  "Assemble",
  "Agitate",
  "Addict",
  "Array",
  "Alight",
  "Amidst",
  "Astonish",
  "Anguish",
  "Azalea",
  "Amigo",
  "Absorb",
  "Armored",
  "Ample",
  "Astronomy",
  "Asylum",
  "Adrift",
  "Artist",
  "Accustom",
  "Azure",
  "Alphabet",
  "Aspire",
  "Ardent",
  "Abyss",
  "Animate",
  "Appease",
  "Anchor",
  "Arcade",
  "Ache",
  "Alloy",
  "Airtight",
  "Armadillo",
  "Avid",
  "Absorb",
  "Acorn",
  "Acoustic"
]
let RandText = [
  "y","0", "kitagawa"
];
let  word_array = [
  'Apple', 'Cat', 'Bicycle', 'Sunshine', 'Ocean', 'Music', 'Laughter', 'Mountain', 'Book', 'Adventure',
  'Delicious', 'Friendship', 'Serenade', 'Garden', 'Butterfly', 'Harmony', 'Whisper', 'Chocolate', 'Raindrop', 'Discovery',
  'Smile', 'Dream', 'Sparkle', 'Wanderlust', 'Moonlight', 'Courage', 'Reflection', 'Peaceful', 'Radiant', 'Celebration',
  'Tranquility', 'Freedom', 'Journey', 'Inspiration', 'Velvet', 'Enchantment', 'Blossom', 'Symphony', 'Serenity', 'Euphoria',
  'Captivate', 'Twilight', 'Miracle', 'Passion', 'Vibrant', 'Whisper', 'Graceful', 'Delight', 'Wonder', 'Tranquil',
  'Sunrise', 'Velvet', 'Graceful', 'Captivate', 'Euphoria', 'Blossom', 'Enchantment', 'Serenity', 'Symphony', 'Miracle',
  'Passion', 'Vibrant', 'Whisper', 'Twilight', 'Wonder', 'Tranquil', 'Sunrise', 'Velvet', 'Graceful', 'Captivate',
  'Euphoria', 'Blossom', 'Enchantment', 'Serenity', 'Symphony', 'Miracle', 'Passion', 'Vibrant', 'Whisper', 'Twilight',
  'Wonder', 'Tranquil', 'Sunrise', 'Velvet', 'Graceful', 'Captivate', 'Euphoria', 'Blossom', 'Enchantment', 'Serenity', 'Symphony',
  'Miracle', 'Passion', 'Vibrant', 'Whisper', 'Twilight', 'Wonder', 'Tranquil', 'Sunrise', 'Love', 'Delicate', 'Thunder',
  'Mystery', 'Silhouette', 'Serendipity', 'Adventure', 'Velvet', 'Tranquility', 'Firefly', 'Gossamer', 'Mesmerize', 'Luminescent',
  'Cascade', 'Enchanting', 'Blissful', 'Effervescent', 'Whimsical', 'Delightful', 'Breathtaking', 'Vibrant', 'Serene', 'Misty',
  'Whisper', 'Meadow', 'Blossom', 'Radiant', 'Joyful', 'Euphoric', 'Sprinkle', 'Sunrise', 'Sparkle', 'Twilight', 'Tranquil',
  'Melody', 'Dancing', 'Harmony', 'Captivating', 'Enthralling', 'Serenade', 'Dreamy', 'Wonder', 'Bliss', 'Whimsy',
  'Luminous', 'Cascade', 'Glimmer', 'Marvel', 'Velvet', 'Ethereal', 'Majestic', 'Enchanted', 'Tranquility', 'Delight',
  'Serene', 'Jubilant', 'Whisper', 'Radiant', 'Enchanting', 'Breathtaking', 'Velvet', 'Graceful', 'Captivate', 'Euphoria',
  'Blossom', 'Enchantment', 'Serenity', 'Symphony', 'Miracle', 'Passion', 'Vibrant', 'Whisper', 'Twilight', 'Wonder',
  'Tranquil', 'Sunrise', 'Velvet', 'Graceful', 'Captivate', 'Euphoria', 'Blossom', 'Enchantment', 'Serenity', 'Symphony',
  'Miracle', 'Passion', 'Vibrant', 'Whisper', 'Twilight', 'Wonder', 'Tranquil', 'Sunrise', 'Velvet', 'Graceful',
  'Captivate', 'Euphoria', 'Blossom', 'Enchantment', 'Serenity', 'Symphony', 'Miracle', 'Passion', 'Vibrant', 'Whisper',
  'Twilight', 'Wonder', 'Tranquil', 'Sunrise', 'Velvet', 'Graceful', 'Captivate', 'Euphoria', 'Blossom', 'Enchantment',
  'Serenity', 'Symphony', 'Miracle', 'Passion', 'Vibrant', 'Whisper', 'Twilight', 'Wonder', 'Tranquil', 'Sunrise',
  'Velvet', 'Graceful', 'Captivate', 'Euphoria', 'Blossom', 'Enchantment', 'Serenity', 'Symphony', 'Miracle', 'Passion',
  'Vibrant', 'Whisper', 'Twilight', 'Wonder', 'Tranquil', 'Sunrise', 'Love', 'Delicate', 'Thunder', 'Mystery', 'Silhouette',
  'Serendipity', 'Adventure', 'Velvet', 'Tranquility', 'Firefly', 'Gossamer', 'Mesmerize', 'Luminescent', 'Cascade', 'Enchanting',
  'Blissful', 'Effervescent', 'Whimsical', 'Delightful', 'Breathtaking', 'Whisper', 'Misty', 'Euphoric', 'Luminescent', 'Delight',
  'Joyful', 'Breathtaking', 'Whimsical', 'Gossamer', 'Radiant', 'Jubilant', 'Tranquil', 'Serenade', 'Blossom', 'Ethereal',
  'Majestic', 'Enthralling', 'Marvel', 'Glimmer', 'Cascade', 'Jubilant', 'Radiant', 'Twilight', 'Enthralling', 'Breathtaking',
  'Delightful', 'Harmony', 'Whimsical', 'Tranquility', 'Marvelous', 'Majestic', 'Serenade', 'Joyful', 'Serene', 'Dancing',
  'Blossom', 'Luminescent', 'Ethereal', 'Gossamer', 'Radiant', 'Dreamy', 'Enchanting', 'Effervescent', 'Sprinkle', 'Whisper',
  'Tranquil', 'Misty', 'Cascade', 'Marvel', 'Luminous', 'Sparkle', 'Enthralling', 'Delight', 'Euphoric', 'Glimmer',
  'Tranquility', 'Blossom', 'Melody', 'Jubilant', 'Serenade', 'Harmony', 'Whimsical', 'Dreamy', 'Ethereal', 'Radiant',
  'Serene', 'Luminescent', 'Misty', 'Tranquil', 'Enthralling', 'Glimmer', 'Sprinkle', 'Marvel', 'Effervescent', 'Cascade',
  'Whisper', 'Sparkle', 'Radiant', 'Tranquility', 'Delightful', 'Serenade', 'Dreamy', 'Luminous', 'Blossom', 'Jubilant',
  'Enchanting', 'Ethereal', 'Gossamer', 'Misty', 'Tranquil', 'Marvelous', 'Serene', 'Whisper', 'Dancing', 'Radiant',
  'Harmony', 'Sprinkle', 'Euphoric', 'Jubilant', 'Effervescent', 'Melody', 'Cascade', 'Serenade', 'Blossom', 'Tranquility',
  'Marvel', 'Enthralling', 'Ethereal', 'Whisper', 'Luminous', 'Delight', 'Joyful', 'Breathtaking', 'Whimsical', 'Gossamer',
  'Radiant', 'Jubilant', 'Tranquil', 'Serenade', 'Blossom', 'Effervescent', 'Cascade', 'Misty', 'Jubilant', 'Sparkle',
  'Whisper', 'Marvel', 'Sprinkle', 'Enchanting', 'Euphoric', 'Delight', 'Tranquility', 'Radiant', 'Blossom', 'Ethereal',
  'Serenade', 'Harmony', 'Glimmer', 'Tranquil', 'Dreamy', 'Serene', 'Luminous', 'Effervescent', 'Dancing', 'Whimsical',
  'Jubilant', 'Misty', 'Sparkle', 'Whisper', 'Marvel', 'Cascade', 'Enchanting', 'Breathtaking', 'Velvet', 'Delightful',
  'Tranquility', 'Marvelous', 'Jubilant', 'Serenade', 'Glimmer', 'Effervescent', 'Dreamy', 'Serene', 'Enthralling', 'Luminous',
  'Blossom', 'Radiant', 'Harmony', 'Sprinkle', 'Euphoric', 'Tranquil', 'Misty', 'Delight', 'Joyful', 'Whimsical',
  'Gossamer', 'Luminescent', 'Cascade', 'Serenade', 'Enchanting', 'Blissful', 'Effervescent', 'Whimsical', 'Delightful', 'Breathtaking',
  'Vibrant', 'Serene', 'Misty', 'Whisper', 'Meadow', 'Blossom', 'Radiant', 'Joyful', 'Euphoric', 'Sprinkle',
  'Sunrise', 'Sparkle', 'Twilight', 'Tranquil', 'Melody', 'Dancing', 'Harmony', 'Captivating', 'Enthralling', 'Serenade',
  'Dreamy', 'Wonder', 'Bliss', 'Whimsy', 'Luminous', 'Cascade', 'Glimmer', 'Marvel', 'Velvet', 'Ethereal',
  'Majestic', 'Enchanted', 'Tranquility', 'Delight', 'Serene', 'Jubilant', 'Whisper', 'Radiant', 'Enchanting', 'Breathtaking',
  'Velvet', 'Graceful', 'Captivate', 'Euphoria', 'Blossom', 'Enchantment', 'Serenity', 'Symphony', 'Miracle', 'Passion',
  'Vibrant', 'Whisper', 'Twilight', 'Wonder', 'Tranquil', 'Sunrise', 'Velvet', 'Graceful', 'Captivate', 'Euphoria',
  'Blossom', 'Enchantment', 'Serenity', 'Symphony', 'Miracle', 'Passion', 'Vibrant', 'Whisper', 'Twilight', 'Wonder',
  'Tranquil', 'Sunrise', 'Velvet', 'Graceful', 'Captivate', 'Euphoria', 'Blossom', 'Enchantment', 'Serenity', 'Symphony',
  'Miracle', 'Passion', 'Vibrant', 'Whisper', 'Twilight', 'Wonder', 'Tranquil', 'Sunrise', 'Velvet', 'Graceful',
  'Captivate', 'Euphoria', 'Blossom', 'Enchantment', 'Serenity', 'Symphony', 'Miracle', 'Passion', 'Vibrant', 'Whisper',
  'Twilight', 'Wonder', 'Tranquil', 'Sunrise', 'Love', 'Delicate', 'Thunder', 'Mystery', 'Silhouette', 'Serendipity',
  'Adventure', 'Velvet', 'Tranquility', 'Firefly', 'Gossamer', 'Mesmerize', 'Luminescent', 'Cascade', 'Enchanting', 'Blissful',
  'Effervescent', 'Whimsical', 'Delightful', 'Breathtaking', 'Vibrant', 'Serene', 'Misty', 'Whisper', 'Meadow', 'Blossom',
  'Radiant', 'Joyful', 'Euphoric', 'Sprinkle', 'Sunrise', 'Sparkle', 'Twilight', 'Tranquil', 'Melody', 'Dancing',
  'Harmony', 'Captivating', 'Enthralling', 'Serenade', 'Dreamy', 'Wonder', 'Bliss', 'Whimsy', 'Luminous', 'Cascade',
  'Glimmer', 'Marvel', 'Velvet', 'Ethereal', 'Majestic', 'Enchanted', 'Tranquility', 'Delight', 'Serene', 'Jubilant',
  'Whisper', 'Radiant', 'Enchanting', 'Breathtaking', 'Velvet', 'Graceful', 'Captivate', 'Euphoria', 'Blossom', 'Enchantment',
  'Serenity', 'Symphony', 'Miracle', 'Passion', 'Vibrant', 'Whisper', 'Twilight', 'Wonder', 'Tranquil', 'Sunrise',
  'Velvet', 'Graceful', 'Captivate', 'Euphoria', 'Blossom', 'Enchantment', 'Serenity', 'Symphony', 'Miracle', 'Passion',
  'Vibrant', 'Whisper', 'Twilight', 'Wonder', 'Tranquil', 'Sunrise', 'Velvet', 'Graceful', 'Captivate', 'Euphoria',
  'Blossom', 'Enchantment', 'Serenity', 'Symphony', 'Miracle', 'Passion', 'Vibrant', 'Whisper', 'Twilight', 'Wonder',
  'Tranquil', 'Sunrise', 'Velvet', 'Graceful', 'Captivate', 'Euphoria', 'Blossom', 'Enchantment', 'Serenity', 'Symphony',
  'Miracle', 'Passion', 'Vibrant', 'Whisper', 'Twilight', 'Wonder', 'Tranquil', 'Sunrise'
]
for(i = 0;i < A_wordsArray.length;i++){
  RandText.push(A_wordsArray[i])
}
let ms = 0;
// text.style.opacity = "0";

const Button = document.getElementsByClassName("key");
for (let i = 0; i < Button.length; i++) {
  Button[i].classList.add(Button[i].innerHTML.trim());
  if (parseFloat(getComputedStyle(Button[i]).gridRow) === 1) {
    Button[i].classList.add("First");
  } else if (parseFloat(getComputedStyle(Button[i]).gridRow) === 2) {
    Button[i].classList.add("Second");
  } else if (parseFloat(getComputedStyle(Button[i]).gridRow) === 3) {
    Button[i].classList.add("Third");
  }
}
// text.focus();
window.addEventListener("keydown", ((e) => {
    // Accurate.style.opacity = "0"
    if (e.keyCode <= 90 && e.keyCode >= 60)
    text.focus();

   if (startSupport === 1) {  
        setInterval(timeCounter,1000)
      }    
  startSupport = 2

    
    
  }))
text.addEventListener("input", function () {
  KeyPress();

  setTimeout(() => {
    checkInput();
    scorer()
  }, 1);
  
});
function checkInput() {
  
  
  // text.value = "";
  const Textvalue = text.value.toUpperCase();
  Right++
  
  const checker = document.getElementById("checker");
  if (Textvalue !== checker.innerHTML.charAt(0))
  {
    checker.classList.add("error")
    setTimeout(() => {
      checker.classList.remove("error")
    },100)
    beep.play()
    Left++;
  
    
    
  }
  if (Textvalue === checker.innerHTML){
    CheckerGonnaCheck();
    
    SpeedSupport++
    } 

    if (Textvalue === checker.innerHTML.charAt(0)) {
 
      animator()
      // prompt("yes");
    
      checker.innerHTML = checker.innerHTML.slice(1);
    }
 
    text.value = "";

  }
  let AnimateSupport = 0;
  function animator(){
    let sakura = []
    for (i = 40; i<60;i++){
      sakura.push(i)
    }
    let kakashi = []
    for (i = 1;i < 20;i++){
      kakashi.push(i)
    }
    let naruto = []
    for(i = 300;i<600;i++){
      naruto.push(i)
    }
    
    let narutoTose
    let negative = [1,-1]
    let negativeIndex = Math.floor(Math.random() * negative.length)
    let RandomIndexX = Math.floor(Math.random() * naruto.length)
    let randomIndexZ = Math.floor(Math.floor(RandomIndexX/sakura.length )) 
      narutoTose = naruto[RandomIndexX] * negative[negativeIndex]
      sakuraTose = sakura[randomIndexZ] * negative[negativeIndex] 
    
   
    let sasuke = []
    for(j = -300; j < 100;j++){
      sasuke.push(j)
    }

    // let randomIndexY = 10
    let randomIndexY = Math.floor(Math.random() * sasuke.length)
    let randomIndexU = Math.floor(Math.floor(randomIndexY/kakashi.length )) 
    let sasukeTose = sasuke[randomIndexY]
    let kakashiTose = kakashi[randomIndexU] 
    // randomly generating an naruto
    let animaon = document.createElement("div");
    animaon.setAttribute("class","Animate");
    container.appendChild(animaon);
    const Animate = document.getElementsByClassName("Animate")[AnimateSupport]
    Animate[10]
    Animate.innerHTML = checker.innerHTML.charAt(0);
    setTimeout(() => {
      
      // Animate.style.translate = narutoTose + "% -"+ 200 + "% "
      Animate.style.translate = narutoTose + "% "+ sasukeTose + "% "
      Animate.style.transform = "perspective(5000px) rotateY(" + sakuraTose  + "deg)"
      +  "rotateX(" + kakashiTose  + "deg)"
    }, 100);
    setTimeout(()=>{
      // Animate.style.translate = "600% -500%"
      Animate.style.translate = (narutoTose * 1.2) + "%" + 500 + "% "
      Animate.style.opacity = "0"
      
    }, 500)
   
   
    AnimateSupport++
  }
  function CheckerGonnaCheck(){
    
    
    // for (x = 0; x <5; i++)
  
    
      const RandTextIndex = Math.floor(Math.random() * RandText.length);
      checker.innerHTML = RandText[RandTextIndex].toUpperCase();
      
    } 
    function enter(E) {
      text.value = E;
      KeyPress();
      checkInput();
    }
    function KeyPress(){
      for (let i = 0; i < Button.length; i++) {
        const Textvalue = text.value.toUpperCase();
        if (Textvalue === Button[i].innerHTML.trim()) {
          Button[i].classList.add("highlighted");
          audioPlay(i,audio)
          setTimeout(function (index) {
            return function () {
              Button[index].classList.remove("highlighted");
            };
          }(i), 235);
          
        }
       
      }
    }
    function audioPlay(e){
      audio[e].play();
      
    }
    function timeCounter(){
      if (ss.innerHTML < 59){

        seconds++;
      }
      else {
        seconds = 0
        minutes++
        
      }
      if (seconds < 10){
        seconds = "0" + seconds
      }
      speedy()
      ss.innerHTML = seconds;
      mm.innerHTML = minutes;
    }
      function scorer(){
        let idiot = 100 -(Left/Right) * 100

        Accurate.innerHTML = idiot.toFixed(2) + "%"
      } 
      function speedy(){
        if (minutes === 0){
          minutes = 1
        }
        let WPMSpeed  = SpeedSupport / minutes 
        WPM.innerHTML = WPMSpeed
      }